baseurl = "http://anasme.github.io"
title = "Anasme's stuff"
theme = "dimension"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = 'Did you try to turn it off and on again ?'
  logo = "fa-terminal"
  copyright = "Anas Asmi"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/asmianas"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/anasasmi/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://anasme.github.io"
